namespace NgProductManager.Forms;

partial class NgCaseDetailForm
{
    private System.ComponentModel.IContainer components = null;
    protected override void Dispose(bool disposing) { if (disposing && components is not null) components.Dispose(); base.Dispose(disposing); }
    private void InitializeComponent()
    {
        Text = "案件詳細"; ClientSize = new Size(1220, 780); MinimumSize = new Size(960, 600); StartPosition = FormStartPosition.CenterParent;
        var root = new TableLayoutPanel { Dock = DockStyle.Fill, Padding = new Padding(12), ColumnCount = 1, RowCount = 4 };
        root.RowStyles.Add(new RowStyle(SizeType.AutoSize)); root.RowStyles.Add(new RowStyle(SizeType.AutoSize)); root.RowStyles.Add(new RowStyle(SizeType.AutoSize)); root.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
        var buttons = new FlowLayoutPanel { AutoSize = true, Margin = new Padding(0, 0, 0, 6) };
        buttonAddReinspection = AddButton(buttons, "再検査結果追加", 130); buttonCloseCase = AddButton(buttons, "検査OK・クローズ", 130); buttonUpdateNotes = AddButton(buttons, "内容修正", 100); buttonAddAttachment = AddButton(buttons, "画像添付", 100); buttonShowAttachments = AddButton(buttons, "添付画像", 100); buttonDeleteCase = AddButton(buttons, "案件削除", 100); root.Controls.Add(buttons, 0, 0);
        var summary = new TableLayoutPanel { AutoSize = true, ColumnCount = 4, Margin = new Padding(0, 0, 0, 6) }; summary.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize)); summary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50)); summary.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize)); summary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50));
        labelLotNumber = AddValue(summary, "ロット番号", 0, 0); labelProductModel = AddValue(summary, "型番", 2, 0); labelProcess = AddValue(summary, "工程", 0, 1); labelStatus = AddValue(summary, "状態", 2, 1); labelRegisteredAt = AddValue(summary, "登録日", 0, 2); labelClosedAt = AddValue(summary, "クローズ日", 2, 2); root.Controls.Add(summary, 0, 1);
        var notes = new GroupBox { Text = "備考", AutoSize = true, Dock = DockStyle.Top, Padding = new Padding(8), Margin = new Padding(0, 0, 0, 6) }; labelNotes = new Label { AutoSize = true, MaximumSize = new Size(1160, 0) }; notes.Controls.Add(labelNotes); root.Controls.Add(notes, 0, 2);
        historyGrid = new DataGridView { Dock = DockStyle.Fill, ReadOnly = true, AllowUserToAddRows = false, AllowUserToDeleteRows = false, AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None, AutoSizeRowsMode = DataGridViewAutoSizeRowsMode.AllCells, BackgroundColor = SystemColors.Window, DefaultCellStyle = { WrapMode = DataGridViewTriState.True }, RowHeadersWidth = 28 };
        foreach (var column in new[] { ("現在", "CurrentState", 80), ("回数", "Sequence", 50), ("検査日", "InspectionDateTime", 90), ("結果", "Result", 55), ("NG理由", "DefectReasonName", 130), ("NG詳細", "DefectDetails", 250), ("処置", "ActionTypeName", 130), ("処置詳細", "ActionDetails", 250), ("担当者", "InspectorName", 100) }) historyGrid.Columns.Add(new DataGridViewTextBoxColumn { HeaderText = column.Item1, DataPropertyName = column.Item2, Width = column.Item3, DefaultCellStyle = { WrapMode = DataGridViewTriState.True } }); historyGrid.RowPrePaint += (_, e) => { if (e.RowIndex == 0) { var row = historyGrid.Rows[e.RowIndex]; row.DefaultCellStyle.BackColor = Color.LightGoldenrodYellow; row.DefaultCellStyle.ForeColor = Color.DarkBlue; } }; bindingSource = new BindingSource(); historyGrid.DataSource = bindingSource; root.Controls.Add(historyGrid, 0, 3); Controls.Add(root);
        buttonAddReinspection.Click += buttonAddReinspection_Click; buttonCloseCase.Click += buttonCloseCase_Click; buttonUpdateNotes.Click += buttonUpdateNotes_Click; buttonAddAttachment.Click += buttonAddAttachment_Click; buttonShowAttachments.Click += buttonShowAttachments_Click; buttonDeleteCase.Click += buttonDeleteCase_Click;
    }
    private static Button AddButton(FlowLayoutPanel panel, string text, int width) { var b = new Button { Text = text, Width = width, Margin = new Padding(0, 0, 6, 0) }; panel.Controls.Add(b); return b; }
    private static Label AddValue(TableLayoutPanel panel, string text, int column, int row) { panel.Controls.Add(new Label { Text = text, AutoSize = true, Margin = new Padding(0, 4, 8, 4) }, column, row); var value = new Label { AutoSize = true, Margin = new Padding(0, 4, 20, 4) }; panel.Controls.Add(value, column + 1, row); return value; }
    private Label labelLotNumber = null!, labelProductModel = null!, labelProcess = null!, labelStatus = null!, labelRegisteredAt = null!, labelClosedAt = null!, labelNotes = null!; private Button buttonAddReinspection = null!, buttonCloseCase = null!, buttonUpdateNotes = null!, buttonAddAttachment = null!, buttonShowAttachments = null!, buttonDeleteCase = null!; private DataGridView historyGrid = null!; private BindingSource bindingSource = null!;
}
